### ISSUE TITLE
Github client_id and client_secret are out in open.

### ISSUE THREAD

**Issue by anuraginvest** [hereisnaman/gitfame#1]
In the code base at https://github.com/hereisnaman/gitfame/blob/master/src/app-main/app-main.html#L238, github client_id and client_secret are out in open. You should ideally use env variable for these.

**Comment by hereisnaman** [comment]
Hi thanks for rising the issue. I am working on building a backend and for the app so that all the fetches will be done from there. The front end will be changed in some time.
