### ISSUE TITLE
Does this app actually works ????

### ISSUE THREAD

**Issue by abacusMark** [hereisnaman/gitfame#3]
Tried your github handle name ... It showed error.

**Comment by hereisnaman** [comment]
Actually the deployed backend is broken. Have to do a push. It works. And I have been developing it for  more.

**Comment by abacusMark** [comment]
Please don't close the issue without fixing it

**Comment by hereisnaman** [comment]
@abacusMark there isn't any error in the code. It is working perfectly fine. Try running it locally first.
