### ISSUE TITLE
Update delay

### ISSUE THREAD

**Issue by AmrMKayid** [hereisnaman/gitfame#39]
After pressing update button it doesn't update the info at the same time

Also, I think it would be better if it gets the updated info immediately 
when I search for someone, not waiting one day to show press button to update it!

**Comment by hereisnaman** [comment]
@AmrMKayid the update request pulls fresh data from github and generate analysis report, It takes time. For some users it even takes 30 secs for the fresh data fetch from github.

Also there is a rate limit of 5000 points for the github api, so there is need to control the fresh data fetches by only allowing once a day.
