### ISSUE TITLE
Add Latest searches cards on Home Page

### ISSUE THREAD

**Issue by 0xnmn** [hereisnaman/gitfame#42]
Add user stats card on home page (right side) for the latest searches. Show user img, username, bio, repo count, followers, PR count, issue count.

Take inspiration from sliding cards on online.codingblocks.com, also make them auto slide in a loop.

Fetch data from latestUsers query. 

This needs to be completed first : https://github.com/hereisnaman/api.gitfa.me/issues/25

**Comment by Dhroov7** [comment]
@hereisnaman I am working on this!!

**Comment by kapillamba4** [comment]
working on this

**Comment by kapillamba4** [comment]
@hereisnaman, [react-coverflow](http://andyyou.github.io/react-coverflow/) good for this?
![image](https://user-images.githubusercontent.com/20877996/40323968-aa5480ee-5d54-11e8-9945-ba76c16aa9a4.png)

**Comment by 0xnmn** [comment]
@kapillamba4 its not that reactive and smooth, go for better implementation, I would prefer it to be done without external component. The cards at <https://online.codingblocks.com> will be good.

**Comment by kapillamba4** [comment]
@hereisnaman, how is this: 
![image](https://user-images.githubusercontent.com/20877996/40377083-9f0d47e8-5e0d-11e8-88fb-d7ceb99b9c41.png)

**Comment by 0xnmn** [comment]
@kapillamba4 this looks better. Get this working and work on the css part, also it should be on auto loop, don't neat the header.
